name: 'Flutter/Swift iOS app: build and publish'
on: 
  push:
    branches:
      - master
    tags:        
      - '**' 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setting release version
        id: set-release-version
        run: |
          echo "RELEASE_VERSION=$(date +%y.%m.%d).${{ github.run_number }}" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +%y.%m.%d)" >> $GITHUB_ENV
      - name: "Current release ${{ env.RELEASE_VERSION }} from ${{ github.ref_name }}"
        run: echo "Current release ${{ env.RELEASE_VERSION }} from ${{ github.ref_name }}"

      ### Skipping installing the Apple certificate and provisioning profile. Not neccesary for this case.
      ### Apple Developer Program Enrollment: We are unable to process your request. An unknown error occurred.
      ### - name: Installing Apple certificate
      ###   uses: apple-actions/import-codesign-certs@v2
      ###   with:
      ###     p12-file-base64: ${{ secrets.P12_BASE64 }}
      ###     p12-password: ${{ secrets.P12_PASSWORD }}
      ### - name: Installing the provisioning profile
      ### ...

      - name: Installing Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Getting the current package's dependencies
        run: flutter pub get

      - name: Building an iOS archive bundle (without IPA for distribution)
        run: flutter build ipa --release --build-number "${{ github.run_number }}" --build-name="${{ env.RELEASE_DATE }}" --no-codesign --export-method ad-hoc 

      ### Extra xcodebuild steps, not using xcodebuild for this case.
      # - name: Build resolve Swift dependencies
      #   run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release
      #
      # - name: Build xcArchive for re-signing it from the client's side with their own profile and certificate
      #   run: |
      #     xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release  -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath build/fapp.${{ env.RELEASE_VERSION }}.xcarchive clean archive \
      #       CODE_SIGN_IDENTITY="" \
      #       CODE_SIGNING_REQUIRED=NO \
      #       CODE_SIGNING_ALLOWED=NO \
      #       CODE_SIGN_ENTITLEMENTS="" 
      #
      ### Skipping an archive distribution because of no certificates
      ### - name: Exporting ipa
      ###   run: xcodebuild -exportArchive -archivePath build/fapp.${{ env.RELEASE_VERSION }}.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build-ipa/fapp.${{ env.RELEASE_VERSION }}.ipa

      - name: Post-build bundle renaming
        run: mv build/ios/archive/Runner.xcarchive ./fapp.${{ env.RELEASE_VERSION }}.xcarchive
      - name: Archiving
        run: zip --quiet --recurse-paths fapp.${{ env.RELEASE_VERSION }}.xcarchive.zip ./fapp.${{ env.RELEASE_VERSION }}.xcarchive/

      - name: Creating Github Release artefacts for signing and releasing later by the client
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: true
          files: |
            fapp.${{ env.RELEASE_VERSION }}.xcarchive.zip

      ### Skipping Cleanup: removing the certificate and provisioning profile from the runner because of no certificates for this case.
